QT_ARCH = x86_64
QT_BUILDABI = x86_64-little_endian-lp64
QT.global.enabled_features = c++11 c++14 c99 c11 thread future concurrent static
QT.global.disabled_features = cross_compile framework shared rpath appstore-compliant debug_and_release simulator_and_device build_all c++1z pkg-config force_asserts separate_debug_info
CONFIG += release static
QT_CONFIG += release c++11 c++14 concurrent dbus no-pkg-config reduce_exports reduce_relocations static stl
QT_VERSION = 5.12.0
QT_MAJOR_VERSION = 5
QT_MINOR_VERSION = 12
QT_PATCH_VERSION = 0
QT_GCC_MAJOR_VERSION = 4
QT_GCC_MINOR_VERSION = 2
QT_GCC_PATCH_VERSION = 1
QT_CLANG_MAJOR_VERSION = 6
QT_CLANG_MINOR_VERSION = 0
QT_CLANG_PATCH_VERSION = 1
QT_EDITION = OpenSource
